# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
       migrations.CreateModel(
            name='VideoQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.IntegerField(default=0)),
                ('clipduration', models.IntegerField(default=0)),
            ],
        ),
    ]
