# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161029_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoqueue',
            old_name='clipdurations',
            new_name='clipduration',
        ),
    ]
