# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20161029_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoqueue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
