# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_videoqueue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
