# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20161029_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoqueue',
            name='clipurl',
            field=models.CharField(default=b'frame.png', max_length=30),
        ),
    ]
