# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_videoqueue_clipurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='channel',
            field=models.IntegerField(default=0),
        ),
    ]
